# Generated by Django 2.2 on 2020-06-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=15, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=15, verbose_name='Отчество')),
                ('photo', models.ImageField(upload_to='upload', verbose_name='Фото')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('short_biography', models.TextField(verbose_name='Краткая биография')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('date_start', models.DateField(verbose_name='Дата начала')),
                ('date_end', models.DateField(verbose_name='Дата окончания')),
                ('max_count_vote', models.IntegerField(blank=True, verbose_name='Максимальное количество голосов')),
                ('character', models.ManyToManyField(blank=True, null=True, to='vote.Character', verbose_name='Персонаж')),
            ],
        ),
    ]
