# Generated by Django 2.2 on 2020-06-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='vote_count',
            field=models.IntegerField(default=0, verbose_name='Количество голосов'),
        ),
    ]
