# Generated by Django 2.2 on 2020-06-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_character_vote_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-vote_count']},
        ),
        migrations.AlterField(
            model_name='vote',
            name='max_count_vote',
            field=models.IntegerField(blank=True, null=True, verbose_name='Максимальное количество голосов'),
        ),
    ]
