# Generated by Django 2.2 on 2020-07-06 10:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_auto_20200629_2209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['-vote_count'], 'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': 'Голосование', 'verbose_name_plural': 'Голосования'},
        ),
        migrations.RemoveField(
            model_name='character',
            name='age',
        ),
        migrations.AddField(
            model_name='character',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
